### ISSUE TITLE
End of input

### ISSUE THREAD

**Issue by techiesatish** [KudzieChase/KotlinCoroutinesRetrofit#1]
I have implemented this in a dummy project . I am using json value to login in my App but I am getting End of character in response.
**RestrofitService**

  @POST("/****/services/testing.php")
    fun getPosts(@Body jsonRequest: String): Deferred<Response<Feedbacks>>

**Login  Method**
 private fun initLogin() {
        val service = RetrofitFactory.makeRetrofitService()
        GlobalScope.launch(Dispatchers.Main) {
            val request = service.getPosts(Utils.jsonRequest(et_loginId.text.toString(),et_loginPwd.text.toString()))
            try {
                val response = request.await()
                response.body()?.let {
                    toast("Hii")
                }
            } catch (e: HttpException) {
                toast(e.code())
            } catch (e: Throwable) {
                toast(e.message.toString())  //this toast showing
            }
        }
    }

**Response JSON Format** I am successfully getting when I am hitting URL.
{
    "status": 1,
    "message": "success",
    "data": {
        "sno": "1",
        "unique_user_id": "1",
        "username": "krishna",
        "password": "AHUnB49vJMlhKk69w/Kpnw==",
        "name": "krishna",
        "mobile": "123",
        "date": "2019/02/06",
        "visible": "1"
    }
}

**Data Class of Feedback** I just want to get status of response. So I have only used status and message.

data class Feedbacks(@SerializedName("status") var status: Int, @SerializedName("message") var message: String)

**Comment by KudzieChase** [comment]
Hello @techiesatish 

- I am noticing that you did not wrap your feedback class in your response object. 

- Secondly I will push a change just now to how one must properly make a request using coroutines.

In my first point I believe 
```
@post("/****/services/testing.php")
fun getPosts(@Body jsonRequest: String): Deferred<Response>
```

Should be 
```
@POST("/****/services/testing.php")
fun getPosts(@Body jsonRequest: String): Deferred<Response<Feedbacks>>
```

Then to my second point I am updating the code for making the request as follows:

```
CoroutineScope(Dispatchers.IO).launch {
    val request = service.getPosts()
    withContext(Dispatchers.Main) {
        //do something with result like updating the UI
    }
}
```

Let me know if point one fixes your issue. If it does not, please show me what is returned from the Okhttp response interceptor in your logs.
